const express = require('express');
const cors = require('cors');
const app = express();
app.use(cors());

app.get('/api/movies', cors(), (req, res) => {
  const movies = [
    {id: 1, url: "https://www.tvmaze.com/shows/1/under-the-dome", name: "Under the Dome", genres: ["Drama", "Science-Fiction", "Thriller"], runtime: 60, premiered: "2013-06-24", officialSite: "http://www.cbs.com/shows/under-the-dome/", image: { medium: "https://static.tvmaze.com/uploads/images/medium_portrait/81/202627.jpg", original: "https://static.tvmaze.com/uploads/images/original_untouched/81/202627.jpg" }, summary: "<p><b>Under the Dome</b> is the story of a small town that is suddenly and inexplicably sealed off from the rest of the world by an enormous transparent dome. The town's inhabitants must deal with surviving the post-apocalyptic conditions while searching for answers about the dome, where it came from and if and when it will go away.</p>"},
    {id: 2, url: "https://www.tvmaze.com/shows/2/person-of-interest", name: "Person of Interest", genres: ["Action", "Crime", "Science-Fiction"], runtime: 60, premiered: "2011-09-22", officialSite: "http://www.cbs.com/shows/person_of_interest/", image: { medium: "https://static.tvmaze.com/uploads/images/medium_portrait/163/407679.jpg", original: "https://static.tvmaze.com/uploads/images/original_untouched/163/407679.jpg" }, summary: "<p>You are being watched. The government has a secret system, a machine that spies on you every hour of every day. I know because I built it. I designed the Machine to detect acts of terror but it sees everything. Violent crimes involving ordinary people. People like you. Crimes the government considered \"irrelevant\". They wouldn't act so I decided I would. But I needed a partner. Someone with the skills to intervene. Hunted by the authorities, we work in secret. You'll never find us. But victim or perpetrator, if your number is up, we'll find you.</p>"},
    {id: 3, url: "https://www.tvmaze.com/shows/3/bitten", name: "Bitten", genres: ["Drama", "Horror", "Romance"], runtime: 60, premiered: "2014-01-11", officialSite: "http://bitten.space.ca/", image: { medium: "https://static.tvmaze.com/uploads/images/medium_portrait/0/15.jpg", original: "https://static.tvmaze.com/uploads/images/original_untouched/0/15.jpg" }, summary: "<p>Based on the critically acclaimed series of novels from Kelley Armstrong. Set in Toronto and upper New York State, <b>Bitten</b> follows the adventures of 28-year-old Elena Michaels, the world's only female werewolf. An orphan, Elena thought she finally found her \"happily ever after\" with her new love Clayton, until her life changed forever. With one small bite, the normal life she craved was taken away and she was left to survive life with the Pack.</p>" },
    {id: 4, url: "https://www.tvmaze.com/shows/4/arrow", name: "Arrow", genres: ["Drama", "Action", "Science-Fiction"], runtime: 60, premiered: "2012-10-10", officialSite: "http://www.cwtv.com/shows/arrow",  image: { medium: "https://static.tvmaze.com/uploads/images/medium_portrait/213/534017.jpg", original: "https://static.tvmaze.com/uploads/images/original_untouched/213/534017.jpg" }, summary: "<p>After a violent shipwreck, billionaire playboy Oliver Queen was missing and presumed dead for five years before being discovered alive on a remote island in the Pacific. He returned home to Starling City, welcomed by his devoted mother Moira, beloved sister Thea and former flame Laurel Lance. With the aid of his trusted chauffeur/bodyguard John Diggle, the computer-hacking skills of Felicity Smoak and the occasional, reluctant assistance of former police detective, now beat cop, Quentin Lance, Oliver has been waging a one-man war on crime.</p>" },
    {id: 5, url: "https://www.tvmaze.com/shows/5/true-detective", name: "True Detective", genres: ["Drama", "Crime", "Thriller"], runtime: 60, premiered: "2014-01-12", officialSite: "http://www.hbo.com/true-detective", image: { medium: "https://static.tvmaze.com/uploads/images/medium_portrait/178/445621.jpg", original: "https://static.tvmaze.com/uploads/images/original_untouched/178/445621.jpg" }, summary: "<p>Touch darkness and darkness touches you back. <b>True Detective</b> centers on troubled cops and the investigations that drive them to the edge. Each season features a new cast and a new case.</p>" },
    {id: 6, url: "https://www.tvmaze.com/shows/6/the-100", name: "The 100", genres: ["Action", "Adventure", "Science-Fiction"], runtime: 60, premiered: "2014-03-19", officialSite: "http://www.cwtv.com/shows/the-100/", image: { medium: "https://static.tvmaze.com/uploads/images/medium_portrait/257/642675.jpg", original: "https://static.tvmaze.com/uploads/images/original_untouched/257/642675.jpg" }, summary: "<p>Ninety-seven years ago, nuclear Armageddon decimated planet Earth, destroying civilization. The only survivors were the 400 inhabitants of 12 international space stations that were in orbit at the time. Three generations have been born in space, the survivors now number 4,000, and resources are running out on their dying \"Ark\" - the 12 stations now linked together and repurposed to keep the survivors alive. Draconian measures including capital punishment and population control are the order of the day, as the leaders of the Ark take ruthless steps to ensure their future, including secretly exiling a group of 100 juvenile prisoners to the Earth's surface to test whether it's habitable.</p>"},
    {id: 7, url: "https://www.tvmaze.com/shows/7/homeland", name: "Homeland", genres: ["Drama", "Thriller", "Espionage"], runtime: 60, premiered: "2011-10-02", officialSite: "http://www.sho.com/sho/homeland/home", image: { medium: "https://static.tvmaze.com/uploads/images/medium_portrait/230/575652.jpg", original: "https://static.tvmaze.com/uploads/images/original_untouched/230/575652.jpg" }, summary: "<p>The winner of 6 Emmy Awards including Outstanding Drama Series, <b>Homeland</b> is an edge-of-your-seat sensation. Marine Sergeant Nicholas Brody is both a decorated hero and a serious threat. CIA officer Carrie Mathison is tops in her field despite being bipolar. The delicate dance these two complex characters perform, built on lies, suspicion, and desire, is at the heart of this gripping, emotional thriller in which nothing short of the fate of our nation is at stake.</p>" },
    {id: 8, url: "https://www.tvmaze.com/shows/8/glee", name: "Glee", genres: ["Drama", "Music", "Romance"], runtime: 60, premiered: "2009-05-19", officialSite: "http://www.fox.com/glee", image: { medium: "https://static.tvmaze.com/uploads/images/medium_portrait/0/73.jpg", original: "https://static.tvmaze.com/uploads/images/original_untouched/0/73.jpg" }, summary: "<p><b>Glee </b>is a musical comedy about a group of ambitious and talented young adults in search of strength, acceptance and, ultimately, their voice.</p>" },
    {id: 9, url: "https://www.tvmaze.com/shows/9/revenge", name: "Revenge", genres: ["Drama", "Thriller", "Mystery"], runtime: 60, premiered: "2011-09-21", officialSite: null, image: { medium: "https://static.tvmaze.com/uploads/images/medium_portrait/82/206879.jpg", original: "https://static.tvmaze.com/uploads/images/original_untouched/82/206879.jpg" }, summary: "<p>This is not a story about forgiveness; <b>Revenge</b> is a show about retribution. Meet Emily Thorne, the newest resident of The Hamptons. When she was a little girl (and known as Amanda Clarke) her father, David Clarke, was framed for a horrific crime and subsequently sent to prison. While serving his time, the conspirators plotted and murdered David in order to prevent the truth from coming out. Emily is now back with a new identity and ready to take vengeance on the people that murdered her father and stole her childhood.</p>" },
    //{id: 10, firstName: 'John', lastName: 'Doe'},
    //{id: 11, firstName: 'Brad', lastName: 'Traversy'},
    //{id: 12, firstName: 'Mary', lastName: 'Swanson'},
  ];

  res.json(movies);
});

const port = 5000;

app.listen(port, () => `Server running on port ${port}`);